name: Deploy static HTML to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'territoryhierarchy'          # exactly as in the portal
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # secret containing full XML
          package: .   # folder with index.html
