name: Deploy single HTML file to Azure Web App - territoryhierarchy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # show what's in the workspace (optional, helps debug)
      - name: Show files
        run: ls -l

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'territoryhierarchy'
          package: '.'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_9C3C458DA5D949FF8C668512B048F7B6 }}
